FROM node:18.0.0-alpine
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm i
RUN npm i -g concurrently

COPY . .

RUN npx prisma generate



# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs
# USER nextjs

EXPOSE 3000
EXPOSE 3001

CMD ["concurrently", "npm:dev:next", "npm:dev:ws"]
