import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Modal from "../components/Modal";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  const [modalOpen, setModalOpen] = useState(false);
  const closeModal = () => setModalOpen(false);
  const openModal = () => setModalOpen(true);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={openModal}>OPEN</button>
        <Modal isOpen={modalOpen} close={closeModal} />
      </main>
    </>
  );
};

export default Home;
