import Head from "next/head";
import { useNotificationStore } from "../providers/NotifcationProvider";
import { trpc } from "../utils/trpc";
import NotificationCenter from "./Notifications/NotificationCenter";

export default function Layout({ children }: { children: React.ReactNode }) {
  const pushNotification = useNotificationStore(
    (state) => state.pushNotification
  );

  trpc.useSubscription(["game.invite.streamReceivedInvites"], {
    onNext: (data) => {
      pushNotification({
        type: "GameInvite",
        data,
      });
    },
  });

  return (
    <>
      <Head>
        <title>WTTF</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NotificationCenter />
      <div className="h-screen max-h-screen flex flex-col">
        <nav className="w-full h-16 bg-white border-b"></nav>
        <div className="grow overflow-y-auto flex flex-col">
          <main className="relative grow bg-slate-100 flex items-center justify-center">
            {children}
          </main>
          <footer></footer>
        </div>
      </div>
    </>
  );
}
