import Head from 'next/head';
import { useNotificationStore } from '../providers/NotifcationProvider';
import { trpc } from '../utils/trpc';
import Header from './Header';
import NotificationCenter from './Notifications/NotificationCenter';

export default function Layout({ children }: { children: React.ReactNode }) {
  const pushNotification = useNotificationStore(
    (state) => state.pushNotification,
  );

  trpc.useSubscription(['game.invite.streamReceivedInvites'], {
    onNext: (data) => {
      pushNotification({
        type: 'GameInvite',
        data,
      });
    },
  });

  return (
    <>
      <Head>
        <title>WTTF</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen max-h-screen flex flex-col">
        <div className="grow overflow-y-auto flex flex-col">
          <Header />
          <main className="relative grow flex flex-col sm:p-6">
            <NotificationCenter />
            {children}
          </main>
          <footer></footer>
        </div>
      </div>
    </>
  );
}
